### ISSUE TITLE
Cannot inject in Spring Boot

### ISSUE THREAD

**Issue by stylepatrick** [tronprotocol/trident#5]
I am not able to inject the dependencies in Spring Boot 2. Does anyone have a similar issue then me?![image](https://user-images.githubusercontent.com/52086629/114067075-b1308800-989c-11eb-8869-dba390e871d5.jpeg)

**Comment by Starsakary** [comment]
Trident-java is not included in the maven central repo.
Check if you had correctly configured the maven source as `jcenter` and `https://dl.bintray.com/tridentjava/trident/org/tron/trident/`

**Comment by stylepatrick** [comment]
After adding:
`
...
<repositories>
		<repository>
			<id>jcenter</id>
			<name>jcenter</name>
			<url>https://jcenter.bintray.com</url>
		</repository>
		<repository>
			<id>bintray</id>
			<name>bintray</name>
			<url>https://dl.bintray.com/tridentjava/trident/org/tron/trident/</url>
		</repository>
	</repositories>
...
`
to my pom it worked. 

Unfortunately i still dont see the org.tron.trident.core in my external libraries and can not inject the "ApiWrapper". 

![image](https://user-images.githubusercontent.com/52086629/114517431-a11efc80-9c3e-11eb-94d2-9456f1bd07e7.png)

**Comment by Starsakary** [comment]
We've just published version 0.1.1, and it has been migrated to a private nexus because Bintray will terminate the service of jcenter and Bintray. You may change jcenter to mavenCentral, and change the maven URL to `http://3.130.234.198:8081/nexus/content/repositories/trident/` to use the newest version.

I will suggest you delete your .m2 directory and try to build the project again.

**Comment by stylepatrick** [comment]
I am able to inject abi and utils but core still missing even i use the pricate repositroy and after deleting the .m2 folder.

**Comment by Starsakary** [comment]
Currently, I can't reproduce that problem. You can download the .jar file manually from that URL, then manually add other dependencies in the pom file.

**Comment by stylepatrick** [comment]
Maybe i am doing something wrong. Do you have a spring boot 2 example where the libraries are injected?

**Comment by Starsakary** [comment]
Unfortunately, there is not. I will highly recommend you to add the dependency manually, it always works.

**Comment by stylepatrick** [comment]
I got it working with adding it manually. Dont know why but the .jar file was always missing in the \.m2\repository\org\tron\trident\core\0.1.1 directory.

Thank you very much for your help.
